version: "3"
services:
  visualizer:
     image: dockersamples/visualizer:stable
     ports:
       - "8080:8080"
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
     deploy:
       placement:
         constraints: [node.role == manager]
     networks:
       - webnet
  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
networks:
  webnet: